### ISSUE TITLE
새로운 미션의 주제를 정하고 대략적인 계획을 세운다. - 9월 27일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#95]
관련 이슈: #94

**Comment by unluckyjung** [comment]
## TODO

- `09월 24일(금) 오후 3시`까지 각자 **최소 주제 1개**를 정해온다.
- 주제만 정하는것이 아닌, 해당 주제로부터 **어떤 메시지**를 담을 수 있는지를 생각해온다 (ex 로또 미션 : 캐싱)
  - 아이디어 주제가 떠오르면 `미션-제작팀` 슬랙 채널 쓰레드에 떠오른 아이디어를 적는다. (자율)
  - 3자가 해당 아이디어를 보고, `해당 주제에는 이런 메시지도 줄 수  추가있겠는데요?` 라는 의견이 있다면, 자유롭게 슬랙에 적어둔다.

---

## 주제 선정, 일정 계획 회의 
> 09월 24일(금) 오후 3시

- 주제 후보중 어떤 주제를 선정할지 결정짓는다.
- 최종 선정된 주제로부터 어떤 메시지를 교육생에게 줄수 있는지를 브레인 스토밍한다.
- 미션 프로토타입 구현, 미션 피드백, 보완한 미션 재구현 등등... 상세 일정을 계획한다.

**Comment by 2SOOY** [comment]
## 주사위 게임

### step1

- 두 명의 플레이어가 주사위 게임에 참여한다.
- 두 명의 플레이어의 닉네임을 입력받는다.
- 플레이어는 주사위 2개를 굴린다.
- 두 개의 주사위 눈이 같으면 현재 라운드에서 획득한 점수를 모두 잃고 라운드를 넘긴다.
- 두 개의 주사위 눈이 다르면 두 개의 주사위 눈의 합을 더하고 점수를 누적한다.
    - 이후 플레이어는 2가지 행동을 취할 수 있다. 
    - 주사위를 굴려서 추가 점수를 획득한다.
    - 주사위 굴리는 것을 멈추고 상대에게 턴을 넘긴다.
- 5번의 라운드가 진행되며 점수의 총합이 가장 높은 사람이 우승한다.
    - 점수의 합이 같을 경우 draw로 표시한다.
- 점수판 도입
    - 매 턴마다 획득한 점수를 기록한다.

### 출력 예시 

플레이어 이름

```
플레이어 2명의 이름을 쉼표(,)로 구분하여 입력해주세요
포츈,언럭키

포츈의 차례입니다.
주사위 결과 : 1, 2
현재 라운드 점수 : 3

주사위를 더 굴리시겠습니까? (y,n)
> y

주사위 결과 : 2, 3
현재 라운드 점수 : 8

주사위를 더 굴리시겠습니까? (y,n)
> y

주사위 결과 : 4, 4
주사위눈이 같으므로 해당 라운드의 점수를 모두 잃었습니다.
현재 라운드 점수 : 0

언럭키의 차례입니다.
주사위 결과 : 6, 5
현재 라운드 점수 : 11

주사위를 더 굴리시겠습니까?(y,n)
> n

총 점수
포츈 : 0점
언럭키 : 11점

===

포츈의 차례입니다.
주사위 결과 : 3, 3
주사위눈이 같으므로 해당 라운드의 점수를 모두 잃었습니다.
현재 라운드 점수 : 0

언럭키의 차례입니다.
주사위 결과 : 1, 5
현재 라운드 점수 : 6

주사위를 더 굴리시겠습니까?(y,n)
> n

총 점수
포츈 : 0점
언럭키 : 17점

===

결과
(승) 언럭키 : 17
(패) 포츈 : 0
```

### step2

- 주사위 개수를 3개로 늘린다.
- 3개의 주사위 눈이 같게 나오면 `현재 점수 * 2` 를 획득한다.
- 점수 획득에 실패하는 조건은 다음과 같다
    - 현재 쓰로우에서 주사위 눈의 합이 이전 쓰로우에서 주사위 눈의 합보다 작다면 현재 라운드에서 획득한 점수를 모두 잃고 턴을 상대에게 넘긴다.
- 5번의 턴이 진행되며, 점수의 총합이 가장 높은 사람이 우승한다.
    - 점수의 합이 같을 경우
        - 쓰로우를 많이한 사람이 승리한다.
        - 쓰로우의 합도 같을 경우 draw로 표시한다.
- 최초 게임 시작시 사용자는 각자가 예측하는 주사위 눈의 후보를 등록한다 (조커)
    - 조커에 해당하는 주사위 눈의 조합이 나올 경우 점수 획득 룰은 무시하고 100점의 보너스 점수를 얻게된다.

## 어떤 메시지를 교육생에게 줄수 있는지

BE

1. TDD 연습
    - 어떻게 하면 랜덤이 들어간 테스트를 작성할 수 있을지 고민한다.
    - 짧지 않은 플로우를 가지면서 랜덤에 많은 부분을 의존하기 때문에 수동 테스트하기 어렵다. 따라서 테스트 코드의 중요성을 느낄 수 있다.
2. 작은 도메인을 가진 미션을 구현하면서 자바에 익숙하지 않은 사람들이 자바와 친숙해질 수 있도록 한다.
3. 의미있는 값들(이름을 가져야 하는 값들)을 포장하여 원시값 포장을 경험해보도록 한다.
4. 주사위 객체 캐싱
5. 도메인 객체 분리 및 역할 분리 레이어 나누기
6. 요구사항 변경에 따라 프로그래밍 구조가 변경되는 것을 경험하면서 유연한 구조로 작성해야 할 필요성을 느낀다.

FE
1. 자바스크립트를 통한 UI와 비즈니스 로직간의 핸들링
2. 클린코드 작성법
3. 상태관리 (각 플레이어의 상태 -  매 라운드 점수, 쓰로우 횟수)

## 상세 일정

- [ ]  STEP1
    - [x]  프로토타입을 구현해본다. (`10/01 금 19시 회의`)
    - [x]  구현해본 내용을 바탕으로 요구 사항을 개선한다. (10/05 화)
- [ ]  STEP2
    - [ ]  세부사항을 기획 한다. (10/08 금)
    - [ ]  프로토 타입을 구현해본다 (10/15 금)
    - [ ]  구현해본 내용을 바탕으로 요구 사항을 개선한다 (10/18 월)
- [ ]  제작한 미션을 인수한다. (10/22 금)


---
[회의록](https://rattle-king-c48.notion.site/60fae2c4bc8c4af7962dfa958c780ea2)

**Comment by unluckyjung** [comment]
## 난이도
- 절대 레이싱카 급아니다.
- 적어도 블랙잭급으로 느껴짐

### 기존에 기획한것이 레이싱카보다 훨씬 난이도가 높다고 느끼는 이유
- 상태를 관리해야하는게 상당히 까다롭다.
  - 직전의 주사위 결과를 저장하고 있어야한다.
  - 현재 턴이 누구인지를 저장하고 있어야한다.
  - 턴을 종료하기전까지의 점수도 저장하고 있어야한다.

- 턴 교체에 대한 로직이 들어가야한다. (블랙잭 + 체스 급)


### 난이도 하향 제안
- step1을 레이싱카 급으로 난이도를 내리려면
  - 주사위를 **1회씩만 굴리는 식**으로 변경해야할것 같다. (같은 수 나올시) 0점은 유지
  - 유저 1vs1 보다, 유저 vs 컴퓨터로 변경해야할것 같다.

```
플레이어 이름을 입력해주세요
포츈

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

컴퓨터의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

포츈의 차례입니다.
주사위 결과 : 6, 6
현재까지 얻은 점수 :  3

컴퓨터의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 8
```

- 이정도로 바꾸어야 레이싱카 급 미션으로 난이도 조정이 될것같다.
- step2에서 지금 요구조건을 그대로 가져가거나, 조금 쳐내는게 어떨까 한다.
  - **여기서 뭔가 더 난이도를 올리려고 하는것 아닌것 같다.**

---

## 요구 조건
- 2인 게임일시, 이름이 서로 중복되면 안된다는 조건이 필요해보인다.

---

## 출력 (백엔드)
> 2인의 경우


### 이름 출력
```
플레이어 2명의 이름을 쉼표(,)로 구분하여 입력해주세요
포츈,언럭키

포츈의 차례입니다.
주사위 결과 : 1, 2
현재 라운드 점수 : 3

주사위를 더 굴리시겠습니까? (y,n)
> y

주사위 결과 : 2, 3
현재 라운드 점수 : 8
```


```
주사위를 더 굴리시겠습니까? (y,n)
> y

주사위 결과 : 2, 3
현재 라운드 점수 : 8
```

- 다음과 같이 출력하려면 괜히 컨트롤러쪽 로직이 복잡해진다.(출력에 대한 고민이 생겨버림)
  - `포츈의 차례입니다.` 를 출력하지 않음.

```
포츈의 차례입니다.
주사위 결과 : 1, 2
현재 라운드 점수 : 3

주사위를 더 굴리시겠습니까? (y,n)
> y

포츈의 차례입니다.
주사위 결과 : 2, 3
현재 라운드 점수 : 8
```

```
xx의 차례입니다.
주사위 결과 : x, y
현재 라운드 점수 : z
```

- 이렇게 그냥 xx의 차례입니다를 항상 출력하게 하는게 좋겠다.

### 출력순서

```
포츈의 차례입니다.
주사위 결과 : 3, 3
주사위눈이 같으므로 해당 라운드의 점수를 모두 잃었습니다.
현재 라운드 점수 : 0
```

- 중간에 끼워넣으려니까 괜히 출력이 복잡해진다.

```
포츈의 차례입니다.
주사위 결과 : 3, 3
현재 라운드 점수 : 0
주사위눈이 같으므로 해당 라운드의 점수를 모두 잃었습니다.
```

- 이렇게 순서를 변경하는게 좋아보인다.


### 결과 출력

```
총 점수
포츈 : 0점
언럭키 : 17점

===

결과
(승) 언럭키 : 17
(패) 포츈 : 0
```

- 굳이 이렇게 출력할 필요가 없어보인다.
- 출력에 대한 고민만 더 늘어난다.

```
총 점수
포츈 : 0점
언럭키 : 17점
```

- 이것만 출력해도 충분해보인다.


---

**Comment by unluckyjung** [comment]
# 변경된 요구사항

## Step1

- 최대 N명의 플레이어가 주사위 게임에 참여한다.
- 최대 M번의 턴을 입력받는다.
- N명의 플레이어의 닉네임을 입력받는다.
  - N명간의 이름 중복은 허용되지 않는다.
  - 이름 최소 길이는 S이고, 최대 길이는 K이다.
 
- 매턴마다 플레이어는 입력된 이름 순서대로 주사위 2개를 굴린다.
- 주사위 눈이 같으면 점수를 획득하지 못한다.

```
플레이어 이름을 입력해주세요
포츈,조이,시드

턴을 입력해주세요
2

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

조이의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

시드의 차례입니다.
주사위 결과 : 6, 6
현재까지 얻은 점수 : 0


포츈의 차례입니다.
주사위 결과 : 1, 1
현재까지 얻은 점수 : 3

조이의 차례입니다.
주사위 결과 : 5, 6
현재까지 얻은 점수 : 16

시드의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

총 점수
포츈 : 3 점
조이 : 16 점
시드 : 3 점
```

---

## 의논하고 싶은것
- 레이싱카랑 난이도를 맞추기위해 난이도를 하향하다보니, 레이싱카와 굉장히 유사한 미션이 되었다. 괜찮은가?
- 프론트랑 백이랑 STEP2 방향성을 조금 다르게 가져가도 되는가? 
  - 프론트는 좀더 인터렉셔널한 작업이 있어도됨, 백엔드는 레이싱카 단계에서 이전의 상태를 관리하는것은 난이도가 급상승한다고 느껴져서 인터렉셔널한 작업을 지양하길 바람.
  - 기존의 레이싱카의 경우에도, 프론트는 Step2에서 추가  요구사항이 추가되었음. 그러나 백엔드는 MVC 패턴 적용정도만 요구했었음.


---

## Step2 (미정)

> 룰이 변경된다.  

- 똑같은 dice가 나오기 전까지, 주사위를 계속 굴릴 수 있다.
- 똑같은 dice가 나오면, 결과값을 더하고 턴을 넘긴다.
- 라운드마다 점수를 기록해놓고, 최종 결과때 라운드별 점수를 출력한다.

```
플레이어 이름을 입력해주세요
포츈,조이

턴을 입력해주세요
2

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

주사위 결과 : 4, 5
현재까지 얻은 점수 : 12

주사위 결과 : 6, 6
현재까지 얻은 점수 : 24

---

조이의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

주사위 결과 : 2, 2
현재까지 얻은 점수 : 9

---

포츈의 차례입니다.
주사위 결과 : 1, 1
현재까지 얻은 점수 : 26

---

조이의 차례입니다.
주사위 결과 : 4, 4
현재까지 얻은 점수 : 17

---

결과
1라운드
포츈 : 24
조이 : 9

2라운드
포츈 : 2
조이 : 8

총 점수
포츈 : 26
조이 : 17
```

---

## TODO

- 변경된 STEP1 요구 사항을 구현해오고 주간회의전에 논의한다. (10/05 화 16:00)

**Comment by unluckyjung** [comment]
# (10/05 화 16:00 회의)
> 난이도 하향이 적용된 주사위 게임을 진행한뒤, 각자 느낀점을 공유한다.

## 내용공유

### 난이도 하향
- 기존 기획했던 방향은, 레이싱카와 비교할때 난이도가 높다고 생각이 들어서 난이도 하향을 진행했다.

### Step1
- 난이도 하향을 진행한 Step1

> 매턴마다 플레이어는 입력된 이름 순서대로 주사위 2개를 1번만 굴린다.
> 주사위 눈이 같으면 점수를 획득하지 못한다.
> 주사위를 굴릴때마다 **현재까지 누적 획득한 점수**를 출력한다.
> 최종 결과를 출력한다.

### 라이브러리
- 라이브러리 기능을 의식하지않고 미션을 기획한뒤, 기획이 완료된뒤 미션을 제작한 라이브러리를 통해서 구현해보았는데 자연스러웠다.

---

## 기획에 대한 질문
- 레이싱카랑 난이도를 맞추기위해 난이도를 하향하다보니, 레이싱카와 비슷한 느낌의 미션으로 재구성되었다.
  - 하지만, 직접 구현을 해보니 `주사위 결과 : 1, 2` 를 다루는 부분에서 살짝 다른느낌이 있었고, 완전히 기획 자체가 비슷하다는 느낌보다는, 난이도가 비슷한 미션같은 느낌을 받았다.
  - 미션제작팀 의견으로는 **STEP1은 이대로 픽스하면 좋겠다**라고 결론이 났는데, 코치분들의 의견이 궁금하다.

## STEP2에 대한 의논거리
> 프론트랑 백이랑 STEP2 방향성을 조금 다르게 가져가도 되는가?

- 프론트는 좀더 인터렉셔널한 작업이 있어도됨, 백엔드는 레이싱카 단계에서 이전의 상태를 관리하는것은 난이도가 급상승한다고 느껴져서 인터렉셔널한 작업을 지양하길 바라고 있다.
- 기존의 레이싱카의 경우에도, 프론트는 Step2에서 추가 요구사항이 추가되었음. 그러나 백엔드는 MVC 패턴 적용정도만 요구했었다.

- 지금  `Step2 (미정)`으로 간단한 프로토타입을 하나 만들어 봤는데, 이에대한 피드백도 받고싶다.

### Step2
> 똑같은 dice가 나오기 전까지, 주사위를 계속 굴릴 수 있다.
> 똑같은 dice가 나오면, 결과값을 더하고 턴을 넘긴다.
> 라운드마다 점수를 기록해놓고, 최종 결과때 라운드별 점수를 출력한다.

**Comment by unluckyjung** [comment]
## 일정 (Updated)

- [x]  STEP1
    - [x]  프로토타입을 구현해본다. (`10/01 금 19시 회의`)
    - [x]  구현해본 내용을 바탕으로 요구 사항을 개선한다. `(10/05 화)`
- [ ]  STEP2
    - [x]  세부사항을 기획 한다. `(10/08 금)` 
      - **슬랙**으로 추가적인 아이디어가 있으면 공유, 회의가 필요한 기획안이 나올시 `10/08 금 19:00`에 회의 예정 
      - (별다른 추가 아이디어가 없을시 아래 `프로토 타입을 구현 해본다 (10/12 화 16:00)` 바로 이어 진행 
    - [x]  프로토 타입을 구현 해본다 `(10/12 화 16:00)`
    - [ ]  구현해본 내용을 바탕으로 요구 사항을 개선한다 `(10/18 월)`
- [ ]  제작한 미션을 인수한다. `(10/22 금)`

**Comment by unluckyjung** [comment]
## step2 구현 공통 사항
- step2 레이싱카 보다는 난이도가 높다고 생각했다.

- 일급컬렉션을 사용할수 있는 여지가 엄청 많았다.
  - 점수관리, 결과관리... ETC
  - 로또 미션이랑 좀 어울린다고 생각이 들었다.

### step1 -> step2 난이도가 급격하게 상승했다는 느낌을 받았다.
- 백
  - 기존의 레이싱카의 step1 -> step2 난이도 상승폭보다 많이 크다. 
  - 만약 step2에서 mvc 패턴을 학습하는게 목적이면, 해당 주제에 소홀해질 수 있어 보인다.

- 프론트
  - 자동으로 돌아가는 로직이 추가됨으로써, step1에 비해서 step2에서  전체적인 난이도가 상승했다고 느꼈다.

---

## 의견

### 난이도 조정
- 라운드별 결과를 기록하고 출력하는것보다는, step1 때 처럼 점수 결과만 출력하게 하는건 어떨까?

### 학습 주제 변경
- 학습주제를 TDD, 원시값 포장 이런것보다는, 일급컬렉션 활용에 중점을 두면 어떨까?
  - 다른의견: 현재 미션에서도 TDD, 원시값 포장 등등을 충분히 학습할 수 있다. **학습 주제** 자체를 바꾸기보다는, 미션을 좀 수정하는게 어떨까?

- 추가적인 요구사항을 추가한 난이도 상승보다는, MVC 패턴 적용같은걸로 step2를 가져가는게 좋아보인다.

---

## Q
- 이 미션이, 레이싱카 미션을 대체할 예정인가요?
  - 다른 미션을 대체할 **가능성**이 있다면, 레이싱카 일까요?

- 코치, 다른 근로분들이 여유가 있으시면, 한번 구현 해보시고 피드백을 주실수 있으신가요?

**Comment by woowapark** [comment]
@2SOOY @zereight 

아래 요구사항 기준으로 확인해보았습니다.      
혹시 최종본이 아니라면 수정 부탁드려요!
```
## step1

- 최대 N명의 플레이어가 주사위 게임에 참여한다.
- 최대 M번의 턴을 입력받는다.
- N명의 플레이어의 닉네임을 입력받는다.
    - N명간의 이름 중복은 허용되지 않는다.
    - 이름 최소 길이는 S이고, 최대 길이는 K이다.
- 매턴마다 플레이어는 입력된 이름 순서대로 주사위 2개를 1번만 굴린다.
- 주사위 눈이 같으면 점수를 획득하지 못한다.
- 주사위를 굴릴때마다 **현재까지 누적 획득한 점수**를 출력한다.
- 최종 결과를 출력한다.

## step2

- 똑같은 dice가 나오기 전까지, 주사위를 계속 굴릴 수 있다.
- 똑같은 dice가 나오면, 결과값을 더하고 턴을 넘긴다.
- 라운드마다 점수를 기록해놓고, 최종 결과때 라운드별 점수를 출력한다.
```

- 프론트 기준 & 프리코스 용도라면 step1 으로도 충분할 것 같아요. 
오히려 수정된 버전 기준으로도 step1만으로 자동차 경주보다는 난이도가 높은듯?
    - 덧붙여, 프리코스는 step 구분이 없기 때문에 룰이 변경되는 것과 같은 step2 는 프리코스 용도로는 적절하지 않을 것 같습니다.
    - 레벨1에서 쓰이기 위한 용도를 같이 생각한 부분이라면 
    step1 까지를 끊어서 프리코스용, 
    조금 더 난이도를 추가한 step2까지 포함하는 버전은 레벨1용으로 써도 좋을 것 같습니다.
- 자동차 경주 게임과 유사한 난이도로 내는 것이 의도라면, 프리코스 2주차 기준으로 상태 관리를 해야 하는 요구사항은 최소화하거나 없는 게 맞을 것 같아요. 상태 관리에 대한 학습은 3주차 미션에서.
- 'N명의 플레이어, M번의 턴을 입력받을 수 있다'
    - 최대 N,M 값의 제한이 요구사항에 있는 것일까요?
    - 중간 논의에서는 2명으로 플레이어 수를 제한하는 버전도 있는 것 같은데, 어떤 요구사항을 최종으로 보아야 할까요?
    - 최종 요구사항이 정리되고 나면 출력 UI 예시도 함께 더 정리되어 있으면 좋을 것 같아요! 완성된 어플리케이션을 사용하는 플로우가 정확히 어떤 순서인지, 구현하다보니 애매하게 헷갈리는 부분들이 있더라구요 (사용자 입력 받고 바로 게임 시작인건지, 주사위 던지고 나면 바로 다음 턴으로 이동인지 등등)
- 이름 구분자에 대한 부분이 요구사항에 포함되어야 하지 않을까요?
ex) 플레이어의 닉네임은 쉼표(,)를 기준으로 구분한다.
- '최종 결과를 출력한다.' → '모든 턴이 종료되고 나면 최종 결과를 출력한다.' 로 좀 더 명시적으로 수정하면 어떨까요?-?

개인적으로는 자동차 경주 게임보다 실제 생활에서 경험할 수 있는 상황이라는 생각이 들어 좋았습니다 👍
중간 논의에도 의견이 나온 것처럼 뭔가 더하기보다는     
현재 기준에서 전체적인 난이도를 조정해나가면서 **자동차 경주 게임**을 대체할 수 있는 미션으로 완성해보는 게 어떨까요?

**Comment by unluckyjung** [comment]
@woowapark 

프론트 팀은 아니지만, 공통적으로 고민한 부분에 대해서는 답변드릴 수 있는 부분들이 있더 대신 답변드립니다.

---

> 최대 N,M 값의 제한이 요구사항에 있는 것일까요?  
- 의도적으로 아직 정하지 않았습니다. 코치분들이랑 논의를 해보고 싶어서 미지수로 남겨두었습니다.

<br>

> 중간 논의에서는 2명으로 플레이어 수를 제한하는 버전도 있는 것 같은데, 어떤 요구사항을 최종으로 보아야 할까요?  
- N명으로 봐주시면 됩니다. `,` 를 통해서 구분하기로 결정했었습니다. ex : `포츈,조이,시드` 
  
<br>


> 최종 요구사항이 정리되고 나면 출력 UI 예시도 함께 더 정리되어 있으면 좋을 것 같아요!  

- 입력부분은 `>` 와 같은 표시를 통해서 구분두는것이 좋겠네요. 예리한 피드백 감사드립니다.

<br>

> 이름 구분자에 대한 부분이 요구사항에 포함되어야 하지 않을까요?  
- N명으로 플레이어 수를 정하는것데 대한 답변에서도 `,` 로 구분한다고 말씀드린것을 비추어 보았을때, 요구사항이 포함되어야 되는게 맞습니다.

<br>

>  '모든 턴이 종료되고 나면 최종 결과를 출력한다.' 로 좀 더 명시적으로 수정하면 어떨까요?-?
- 👍 

<br>

피드백 남겨주셔서 감사합니다!

**Comment by woowahan-pjs** [comment]
- https://github.com/woowacourse/javascript-dice
- https://github.com/woowacourse/java-dice

**Comment by unluckyjung** [comment]
## Step1

- 플레이어 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
- 최대 M번의 턴을 입력받는다.
- N명의 플레이어의 닉네임을 입력받는다.
  - N명간의 이름 중복은 허용되지 않는다.
  - 이름 최소 길이는 S이고, 최대 길이는 K이다.
- 매턴마다 플레이어는 입력된 이름 순서대로 주사위 2개를 굴린다.
- 주사위 눈이 같으면 점수를 획득하지 못한다.

```
플레이어 이름을 입력해주세요
> 포츈,조이,시드

턴을 입력해주세요
> 2

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

조이의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

시드의 차례입니다.
주사위 결과 : 6, 6
현재까지 얻은 점수 : 0


포츈의 차례입니다.
주사위 결과 : 1, 1
현재까지 얻은 점수 : 3

조이의 차례입니다.
주사위 결과 : 5, 6
현재까지 얻은 점수 : 16

시드의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

총 점수
포츈 : 3 점
조이 : 16 점
시드 : 3 점
```
---

## Step2

> 룰이 변경된다.  

- 똑같은 dice가 나오기 전까지, 주사위를 계속 굴릴 수 있다.
- 똑같은 dice가 나오면, 결과값을 더하고 턴을 넘긴다.
- 라운드마다 점수를 기록해놓고, 모든 라운드와 턴이 종료되면, 각 라운드별 점수와 최종 결과를 출력한다.


```

플레이어 이름을 입력해주세요
> 포츈,조이

턴을 입력해주세요
> 2

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

주사위 결과 : 4, 5
현재까지 얻은 점수 : 12

주사위 결과 : 6, 6
현재까지 얻은 점수 : 24

---

조이의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

주사위 결과 : 2, 2
현재까지 얻은 점수 : 9

---

포츈의 차례입니다.
주사위 결과 : 1, 1
현재까지 얻은 점수 : 26

---

조이의 차례입니다.
주사위 결과 : 4, 4
현재까지 얻은 점수 : 17

---

결과
1라운드
포츈 : 24
조이 : 9

2라운드
포츈 : 2
조이 : 8

총 점수
포츈 : 26
조이 : 17
```

---

**Comment by 2SOOY** [comment]
## 11/08 정기 회의 안건

1. ~~점수 획득하는 조건에 대한 명시 필요 step1~~
2. ~~라운드에 대한 용어 명시하기~~
3. step1의 코드 퀄리티에 따라  step2에서 코드 변경 범위가 결정
4. ~~이름 관련 조건 지우기 S, K~~
5. ~~똑같은 DICE가 나오기 전까지 주사위를 굴릴 수 있다 -> 굴린다~~
6. 전반적으로 출력문을 봐야 요구사항 파악이 가능해짐 => 요구 사항 개선하기
7. 난이도 관련 프리코스 STEP2 정도가 적절함

**Comment by unluckyjung** [comment]
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa

**Comment by 2SOOY** [comment]
@woowapark @woowahan-pjs 
변경된 요구사항 확인 부탁드립니다 🙏 

## Step1

- 플레이어의 이름을 입력받는다.
  - 플레이어 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다. 
  - 플레이어간 이름 중복은 허용되지 않는다.
- 최대 10번의 라운드를 입력받는다.
- 매 라운드마다 플레이어는 입력된 이름 순서대로 주사위 2개를 굴린다.
- 주사위 눈이 다르면, 두 주사위 눈의 합을 점수로 획득한다.
- 주사위 눈이 같으면, 점수를 획득하지 못한다.
   
```
플레이어 이름을 입력해주세요
> 포츈,조이,시드

라운드를 입력해주세요
> 2

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

조이의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

시드의 차례입니다.
주사위 결과 : 6, 6
현재까지 얻은 점수 : 0


포츈의 차례입니다.
주사위 결과 : 1, 1
현재까지 얻은 점수 : 3

조이의 차례입니다.
주사위 결과 : 5, 6
현재까지 얻은 점수 : 16

시드의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

총 점수
포츈 : 3 점
조이 : 16 점
시드 : 3 점
```
---

## Step2

> 룰이 변경된다.  

- 똑같은 주사위 눈이 나오기 전까지, 주사위를 계속 굴린다.
- 똑같은 주사위 눈이 나오면, 두 주사위 눈의 합을 더해 지금까지 획득한 점수에 추가하고 해당 플레이어의 라운드를 종료한다.
- 모든 라운드가 종료되면, 각 라운드별 점수와 최종 결과를 출력한다.


```

플레이어 이름을 입력해주세요
> 포츈,조이

라운드를 입력해주세요
> 2

포츈의 차례입니다.
주사위 결과 : 1, 2
현재까지 얻은 점수 : 3

주사위 결과 : 4, 5
현재까지 얻은 점수 : 12

주사위 결과 : 6, 6
현재까지 얻은 점수 : 24

---

조이의 차례입니다.
주사위 결과 : 2, 3
현재까지 얻은 점수 : 5

주사위 결과 : 2, 2
현재까지 얻은 점수 : 9

---

포츈의 차례입니다.
주사위 결과 : 1, 1
현재까지 얻은 점수 : 26

---

조이의 차례입니다.
주사위 결과 : 4, 4
현재까지 얻은 점수 : 17

---

결과
1라운드
포츈 : 24
조이 : 9

2라운드
포츈 : 2
조이 : 8

총 점수
포츈 : 26
조이 : 17
```

---

추가 논의 사항
1. STEP2에서 주사위 눈이 다를 경우 주사위 합을 계산하여 점수 합계에 추가하는 문구 추가 필요 여부
2. 라운드 결과에 따른 결과 출력에 대한 요구 사항 명시 필요 여부
